### ISSUE TITLE
Instructions for building a new kernel package?

### ISSUE THREAD

**Issue by figgles** [LordRafa/ALARMOnTegraK1#5]
Hi! It would be really helpful if you could write a guide to building new kernel packages for the Tegra K1. I'd like to follow mainline kernel developments, but I don't know how to build a kernel specifically for the Tegra K1 using arch linux's packaging system.

**Comment by LordRafa** [comment]
I am building a new release, I will provide the commits to diff when is ready. Mostly of the patches are already on the mainline and I suppose we will be able to use repos xorg rather than git

In order to build the kernel you just need to run the following cmd inside "PKGBUILDs/linux-jetson-tk1/"
```bash
makepkg -sC
```
This commit show the changes that I do you change the version bf6994e8e4ff165d64bb802d12ab48b13d764672

But there is a lot of manual working to make things work. Also I couldn't anything remotely stable after kernel 5.8.x that is why I leave this project.
